<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PlatformTarget>x64</PlatformTarget>
	<NoWarn>$(NoWarn);WFAC010;WFO0003</NoWarn>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>TaskbarRunner</AssemblyName>
    <Version>0.2.0</Version>
    <Description>A small, local-only runner on your Windows taskbar.</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TaskbarRunner.Windows.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskbarRunner.Core\TaskbarRunner.Core.csproj" />
  </ItemGroup>
</Project>
